### ISSUE TITLE
Ultra scouter fflogs korean server issue

### ISSUE THREAD

**Issue by Bing-su** [anoyetta/ACT.Hojoring#169]
**Describe the bug**
Because FF14 Korea server is 4.4x, I use hojoring 5.26.6. But I guess this issue would not solved in recent version.

In Ultra scouter - target - fflogs, Ultra scouter gets korean server name 'KrMoogle, KrChocobo, ~' from game, But FFlogs saves korean server name 'Moogle, Chocobo, ~'. So these two are different, Ultra scouter don't show any information. Recently someone makes fixed version plugin and makes it public, I recognized this issue.

**Screenshots**
https://i.imgur.com/CEnMwHk.png

**Environment**
- ACT.Hojoring Version: 5.26.6
- FFXIV_ACT_Plugin Version: 1.7.2.3
 - OS: Window 10 64bit

**Additional context**

**Comment by wozaiha** [comment]
Please change the resources file in “FFZIV_ACT_Plugin.dll”-“WorldList.txt”
manually. Line 536 “2076|KrChocobo” to “2076|Chocobo” and do the same to
moogle line too.
This is a problem that caused by actplugin and happened in CN too.
I wonder whether there is any way to make the plugin support these 2
regions officially.

Bing-su <notifications@github.com>于2019年4月2日 周二20:47写道：

**Comment by anoyetta** [comment]
原則的に韓国、中国クライアントには対応していません。
それぞれ私がテストを行うことが出来ないためです。
以後、韓国、中国専用の対応についてはそちらで修正してPull Requestを送るようにしてください。
グローバル版に影響を与えないことを確認した上で取り込みます。

**Comment by Bing-su** [comment]
Thanks!
