### ISSUE TITLE
Timer going below zero when using Always Show in SPESPE

### ISSUE THREAD

**Issue by Koribi** [anoyetta/ACT.Hojoring#252]
I'm trying to make a Spell Timer with a recast time of 0 that will always show and instead of being reset to a default time with a Keyword I only want it to be extended from 0, so that I can continuously use the same spell to increase the timer without it being reset . This part works as I want it to. The issue is that when the timer hits zero (or if I don't immediately press my intended spell since it starts at zero), it will still count in the background. So if for example 5 seconds have passed since the timer hit zero, when I use the spell again it will count from 10 seconds instead of 15. Is this intended? If not, could you add an option to make the timer stop after it hits 0 if the spell is persistent (always show)?

My goal with this is to be able to create proper timers for spells with Charges. Now, if there is another way to to do that, then that would also be a solution.

Much love,
Koribi

**Comment by sergserg2** [comment]
Same situation. I use Spell Timer with negative extended values (Fell Cleaves from War lowering CD on Infuriate by 5s) and there is mess, because timer don't stop when reaching 0 (I think still count negative values). So when I use next Infuriate (what I set to extend timer for 60s) when timer shows 0, this gives me bad time value (like 30-40s instead 60s).

**Comment by sergserg2** [comment]
OK, there is the way for setting this, no needs for new functionality: https://www.reddit.com/r/ffxiv/comments/chu4z9/guide_for_charged_action_cooldowns_for_special/
